#ifndef BBP_CONSOLE_CHARACTERTYPE_HPP
#define BBP_CONSOLE_CHARACTERTYPE_HPP

//NOTE: Remember to add to CharacterTypeGetter.hpp and Storyteller.hpp

enum class CharacterType {
	NO_CHARACTER=0,
	TEST_CHARACTER,
	WASHERWOMAN,
	LIBRARIAN,
	INVESTIGATOR,
	CHEF,
	EMPATH,
	FORTUNETELLER,
	UNDERTAKER,
	MONK,
	RAVENKEEPER,
	VIRGIN,
	SOLDIER,
	SLAYER,
	POISONER,
	DRUNK
	};

#endif //BBP_CONSOLE_CHARACTERTYPE_HPP
