#ifndef BBP_CONSOLE_CHARACTERTYPE_HPP
#define BBP_CONSOLE_CHARACTERTYPE_HPP

enum class CharacterType {
	NO_CHARACTER=0,
	TEST_CHARACTER,
	WASHERWOMAN,
	LIBRARIAN,
	INVESTIGATOR,
	CHEF,
	EMPATH,
	FORTUNETELLER,
	UNDERTAKER,
	MONK,
	RAVENKEEPER
	};

//TODO: May need template for getting class type from CharacterType

#endif //BBP_CONSOLE_CHARACTERTYPE_HPP
